export const stackLinks: Record<string, string> = {
  TypeScript: "https://www.typescriptlang.org/",
  "Node.js": "https://nodejs.org/",
  NestJS: "https://nestjs.com/",
  Go: "https://go.dev/",
  "Ruby on Rails": "https://rubyonrails.org/",
  PHP: "https://www.php.net/",
  GraphQL: "https://graphql.org/",
  PostgreSQL: "https://www.postgresql.org/",
  MySQL: "https://www.mysql.com/",
  MongoDB: "https://www.mongodb.com/",
  Firebase: "https://firebase.google.com/",
  Vue: "https://vuejs.org/",
  AngularJS: "https://angularjs.org/",
  "React Native": "https://reactnative.dev/",
  Quasar: "https://quasar.dev/",
  Electron: "https://www.electronjs.org/",
  JavaScript: "https://developer.mozilla.org/docs/Web/JavaScript",
  Docker: "https://www.docker.com/",
  AWS: "https://aws.amazon.com/",
  Azure: "https://azure.microsoft.com/",
  Git: "https://git-scm.com/",
  Vitest: "https://vitest.dev/",
  Cypress: "https://www.cypress.io/",
  Scrum: "https://scrumguides.org/",
};
